export const env = {
  KAKAO_JAVASCRIPT_KEY: process.env.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY,
  REDIRECT_URI: process.env.NEXT_PUBLIC_REDIRECT_URI,
  SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  SENTRY_TOKEN: process.env.NEXT_PUBLIC_SENTRY_TOKEN,
  TOPPINGS_TOKEN_KEY: process.env.NEXT_PUBLIC_TOPPINGS_TOKEN_KEY,
  TOPPINGS_SERVER_URL: process.env.NEXT_PUBLIC_TOPPINGS_SERVER_URL,
  TOPPINGS_CLIENT_URL: process.env.NEXT_PUBLIC_TOPPINGS_CLIENT_URL,
  JWT_SECRET_KEY: process.env.NEXT_PUBLIC_JWT_SECRET_KEY,
  GOOGLE_ANALYTICS_TRACKING_ID:
    process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID
} as const;
