# This is a basic workflow to help you get started with Actions

name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    # branches: ["main"]

jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install package dependencies
        run: yarn install

      # Run test cases and this could ensure minimum coverage as well if set
      - name: Execute test cases
        run: yarn test:ci

      - name: Create test build
        run: yarn build
