name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy_preview_client:
    name: "Deploy Storybook per PR"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Validate a project when using Zero-Installs
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

      - name: Build Storybook
        if: ${{ github.event.action != 'closed' }}
        run: |
          yarn workspace client build-storybook
      - name: Deploy preview
        uses: ./.github/workflows/preview-deploy-action
        with:
          type: 스토리북
          source-dir: ./apps/client/storybook-static
          github-event-action: ${{ github.event.action }}
          workspace: "@toppings/client"
